version: '2.1'
services:
    frontend:
        restart: unless-stopped
        build: frontend_dev
        ports:
            - 80:80/tcp
        environment:
            - CERTBOT_EMAIL=${CERTBOT_EMAIL}
        depends_on:
            - cache

    cache:
        restart: unless-stopped
        build:
            context: cache
            args:
                - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
                - AWS_SECRET_KEY=${AWS_SECRET_KEY}
        volumes:
            - /var/log/cache
        expose:
            - 5000
