version: '2.1'
services:
    frontend:
        restart: unless-stopped
        build: frontend
        ports:
            - 80:80/tcp
            - 443:443/tcp
        environment:
            - CERTBOT_EMAIL=${CERTBOT_EMAIL}
        depends_on:
            - cache
            - webhook

    cache:
        restart: unless-stopped
        build:
            context: cache
            args:
                - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
                - AWS_SECRET_KEY=${AWS_SECRET_KEY}
        volumes:
            - /var/log/cache
        expose:
            - 5000

    webhook:
        restart: unless-stopped
        image: staticfloat/docker-webhook
        volumes:
            # Mount this code into /cache.julialang.org
            - ./:/cache.julialang.org
            # Mount the docker socket
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - WEBHOOK_SECRET=${WEBHOOK_SECRET}
            - WEBHOOK_HOOKS_DIR=/cache.julialang.org/hooks
        expose:
            - 8000
